[package]
name = "magic_eye"
version = "0.9.3"
description = "A small gui application Made with Tauri, let you watch stream for a Mediamtx server."
categories = ["utility", "network", "streaming"]
authors = ["Thomas Toulouse"]
license = "MIT"
repository = "https://github.com/Sir-Thom/Magic-eye"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 



[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[dependencies]
tauri = { version = "2.0.6", features = [] }

tauri-plugin-log = { version = "2.0.1" }
tauri-plugin-fs = {  version = "2.0.3" }
tauri-plugin-http = "2.0.3"
tauri-plugin-os = {  version = "2.2.1" }
tauri-plugin-process = { version = "2.0.1" }
dirs-next = "2.0.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
axum = "0.7.7"
tokio = { version = "1.42.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["fs", "cors"] }
#reqwest = "^0.11.23"
open = "5.3.0"
log = "0.4.22"
tauri-plugin-devtools = { version = "2.0.0" }
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols

[lib]
name = "magic_eye_internal_lib"
crate-type = ["rlib"]
